// frontend/src/components/recruiter/ManageApplications.jsx
import { useState, useEffect } from "react";
import toast from "react-hot-toast";
import { X, Users, CheckCircle, XCircle, Clock, FileText } from "lucide-react";
import { getJobApplications, updateApplicationStatus } from "../../api/applicationApi";

/**
 * ManageApplications Modal Component
 * Used by Recruiters to view and update applications for a specific job.
 */
const ManageApplications = ({ isOpen, onClose, job }) => {
  const [applications, setApplications] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    if (isOpen && job) {
      fetchApplications();
    }
  }, [isOpen, job]);

  const fetchApplications = async () => {
    try {
      setLoading(true);
      const res = await getJobApplications(job._id);
      setApplications(res.data.data);
    } catch (err) {
      toast.error("Failed to load applications");
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleStatusChange = async (appId, newStatus) => {
    try {
      await updateApplicationStatus(appId, newStatus);
      toast.success(`Application marked as ${newStatus}`);
      
      // Update local state
      setApplications(apps => apps.map(app => 
        app._id === appId ? { ...app, status: newStatus } : app
      ));
    } catch (err) {
      toast.error("Failed to update status");
    }
  };

  if (!isOpen || !job) return null;

  return (
    <div className="modal-overlay">
      <div className="modal-content profile-form-modal animate-scale-in" style={{ maxWidth: "800px", width: "95%" }}>
        <button className="modal-close" onClick={onClose}>
          <X size={20} />
        </button>
        
        <div className="modal-header">
          <div className="modal-icon-wrapper" style={{ background: "rgba(34, 197, 94, 0.15)", color: "var(--success-500)" }}>
            <Users size={24} />
          </div>
          <div>
            <h2 className="modal-title">Applications</h2>
            <p className="modal-subtitle">Reviewing candidates for <strong>{job.title}</strong></p>
          </div>
        </div>

        <div className="profile-form-body" style={{ maxHeight: "70vh", overflowY: "auto", paddingRight: "10px" }}>
          {loading ? (
            <div style={{ textAlign: "center", padding: "40px" }}>Loading applicants...</div>
          ) : applications.length === 0 ? (
            <div style={{ textAlign: "center", padding: "40px", color: "var(--text-secondary)" }}>
              No applications received yet.
            </div>
          ) : (
            <div className="applications-list" style={{ display: "flex", flexDirection: "column", gap: "15px" }}>
              {applications.map((app) => (
                <div key={app._id} style={{ border: "1px solid var(--border-default)", borderRadius: "8px", padding: "15px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
                  <div>
                    <h4 style={{ margin: "0 0 5px", fontSize: "16px" }}>{app.applicant.name}</h4>
                    <p style={{ margin: "0 0 8px", fontSize: "13px", color: "var(--text-secondary)" }}>{app.applicant.email}</p>
                    
                    <div style={{ display: "flex", gap: "10px", alignItems: "center" }}>
                      <a 
                        href={`http://localhost:5000/api/profile/resumes/${app.resume._id}/download`} 
                        className="badge badge-navy" 
                        style={{ textDecoration: "none", display: "inline-flex", alignItems: "center", gap: "4px" }}
                      >
                        <FileText size={12} /> View Resume
                      </a>
                      
                      <span className="badge" style={{ 
                        background: app.status === "shortlisted" || app.status === "hired" ? "rgba(34, 197, 94, 0.15)" : 
                                    app.status === "rejected" ? "rgba(239, 68, 68, 0.15)" : "var(--cream-200)",
                        color: app.status === "shortlisted" || app.status === "hired" ? "var(--success-500)" : 
                               app.status === "rejected" ? "var(--error-500)" : "var(--text-secondary)"
                      }}>
                        {app.status.toUpperCase()}
                      </span>
                    </div>
                    
                    {app.coverLetter && (
                      <div style={{ marginTop: "10px", padding: "10px", background: "var(--cream-50)", borderRadius: "6px", fontSize: "13px" }}>
                        <strong>Cover Letter:</strong><br/>{app.coverLetter}
                      </div>
                    )}
                  </div>

                  <div style={{ display: "flex", flexDirection: "column", gap: "8px" }}>
                    {app.status !== "shortlisted" && (
                      <button 
                        onClick={() => handleStatusChange(app._id, "shortlisted")}
                        style={{ padding: "6px 12px", background: "rgba(34, 197, 94, 0.1)", color: "var(--success-500)", border: "1px solid rgba(34, 197, 94, 0.3)", borderRadius: "4px", fontSize: "12px", cursor: "pointer", display: "flex", alignItems: "center", gap: "5px" }}
                      >
                        <CheckCircle size={14} /> Shortlist
                      </button>
                    )}
                    {app.status !== "rejected" && (
                      <button 
                        onClick={() => handleStatusChange(app._id, "rejected")}
                        style={{ padding: "6px 12px", background: "rgba(239, 68, 68, 0.1)", color: "var(--error-500)", border: "1px solid rgba(239, 68, 68, 0.3)", borderRadius: "4px", fontSize: "12px", cursor: "pointer", display: "flex", alignItems: "center", gap: "5px" }}
                      >
                        <XCircle size={14} /> Reject
                      </button>
                    )}
                    {app.status === "pending" && (
                      <button 
                        onClick={() => handleStatusChange(app._id, "reviewed")}
                        style={{ padding: "6px 12px", background: "var(--cream-200)", color: "var(--text-primary)", border: "1px solid var(--border-default)", borderRadius: "4px", fontSize: "12px", cursor: "pointer", display: "flex", alignItems: "center", gap: "5px" }}
                      >
                        <Clock size={14} /> Mark Reviewed
                      </button>
                    )}
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default ManageApplications;

// angular-frontend/src/app/features/recruiter/components/manage-applications/manage-applications.component.ts
import { Component, EventEmitter, Input, OnInit, Output, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Job } from '../../../../core/services/job.service';
import { ApplicationService } from '../../../../core/services/application.service';

@Component({
  selector: 'app-manage-applications',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div class="modal-overlay" (click)="close()">
      <div class="modal-content" (click)="$event.stopPropagation()">
        <div class="modal-header">
          <div>
            <h2>Applications</h2>
            <p class="subtitle">For: {{ job?.title }}</p>
          </div>
          <button class="btn-close" (click)="close()">×</button>
        </div>
        
        <div class="modal-body">
          <div *ngIf="loading" class="loading-state">Loading applications...</div>
          
          <div *ngIf="!loading && applications.length === 0" class="empty-state">
            <p>No applications yet for this job.</p>
          </div>

          <div *ngIf="!loading && applications.length > 0" class="app-list">
            <div class="app-card" *ngFor="let app of applications">
              <div class="app-info">
                <h4>{{ app.applicant?.name || 'Unknown User' }}</h4>
                <p>{{ app.applicant?.email }}</p>
                <div class="app-meta">
                  <span class="status-badge" [ngClass]="app.status">{{ app.status }}</span>
                  <span class="date">Applied: {{ app.createdAt | date:'shortDate' }}</span>
                </div>
              </div>
              
              <div class="app-actions">
                <a *ngIf="app.resume?.url" [href]="app.resume.url" target="_blank" class="btn-view-resume">View Resume</a>
                
                <div class="status-controls">
                  <select [value]="app.status" (change)="updateStatus(app._id, $event)" [disabled]="updatingId === app._id">
                    <option value="pending">Pending</option>
                    <option value="reviewed">Reviewed</option>
                    <option value="shortlisted">Shortlisted</option>
                    <option value="rejected">Rejected</option>
                  </select>
                  <span *ngIf="updatingId === app._id" class="updating-text">Saving...</span>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .modal-overlay { position: fixed; inset: 0; background: rgba(0,0,0,0.6); display: flex; align-items: center; justify-content: center; z-index: 1000; padding: 20px; backdrop-filter: blur(4px); }
    .modal-content { background: var(--bg-surface); width: 100%; max-width: 700px; border-radius: 16px; box-shadow: var(--shadow-lg); display: flex; flex-direction: column; max-height: 90vh; overflow: hidden; border: 1px solid var(--border-subtle); }
    .modal-header { padding: 20px 24px; border-bottom: 1px solid var(--border-subtle); display: flex; justify-content: space-between; align-items: flex-start; }
    .modal-header h2 { margin: 0; font-size: 20px; color: var(--navy-900); font-family: var(--font-display); }
    .subtitle { margin: 4px 0 0; font-size: 14px; color: var(--text-secondary); }
    .btn-close { background: transparent; border: none; font-size: 24px; color: var(--text-secondary); cursor: pointer; }
    .modal-body { padding: 24px; overflow-y: auto; }
    .loading-state, .empty-state { padding: 40px; text-align: center; color: var(--text-tertiary); }
    .app-list { display: flex; flex-direction: column; gap: 16px; }
    .app-card { display: flex; justify-content: space-between; align-items: center; padding: 16px; border: 1px solid var(--border-default); border-radius: 12px; flex-wrap: wrap; gap: 16px; background: var(--bg-page); }
    .app-info h4 { margin: 0 0 4px; font-size: 16px; color: var(--navy-900); }
    .app-info p { margin: 0 0 8px; font-size: 14px; color: var(--text-secondary); }
    .app-meta { display: flex; gap: 12px; align-items: center; }
    .status-badge { padding: 4px 10px; border-radius: 20px; font-size: 12px; font-weight: 600; text-transform: capitalize; }
    .status-badge.pending { background: #fef3c7; color: #b45309; }
    .status-badge.reviewed { background: #e0f2fe; color: #0369a1; }
    .status-badge.shortlisted { background: #dcfce7; color: #15803d; }
    .status-badge.rejected { background: #fee2e2; color: #b91c1c; }
    .date { font-size: 12px; color: var(--text-tertiary); }
    .app-actions { display: flex; flex-direction: column; gap: 10px; align-items: flex-end; }
    .btn-view-resume { font-size: 13px; font-weight: 600; color: var(--navy-600); text-decoration: none; }
    .btn-view-resume:hover { text-decoration: underline; }
    .status-controls { display: flex; align-items: center; gap: 8px; }
    select { padding: 6px 10px; border-radius: 6px; border: 1px solid var(--border-default); font-family: inherit; font-size: 13px; }
    .updating-text { font-size: 12px; color: var(--text-tertiary); }
  `]
})
export class ManageApplicationsComponent implements OnInit {
  @Input() job: Job | null = null;
  @Output() closeModal = new EventEmitter<void>();

  appService = inject(ApplicationService);

  loading = true;
  applications: any[] = [];
  updatingId: string | null = null;

  ngOnInit() {
    if (this.job) {
      this.fetchApps();
    }
  }

  fetchApps() {
    this.loading = true;
    this.appService.getJobApplications(this.job!._id).subscribe({
      next: (res) => {
        this.applications = res.data;
        this.loading = false;
      },
      error: (err) => {
        console.error(err);
        this.loading = false;
      }
    });
  }

  updateStatus(appId: string, event: Event) {
    const status = (event.target as HTMLSelectElement).value;
    this.updatingId = appId;
    
    this.appService.updateApplicationStatus(appId, status).subscribe({
      next: (res) => {
        this.updatingId = null;
        // update local state
        const app = this.applications.find(a => a._id === appId);
        if (app) {
          app.status = res.data.status;
        }
      },
      error: (err) => {
        console.error(err);
        this.updatingId = null;
        alert('Failed to update status');
      }
    });
  }

  close() {
    this.closeModal.emit();
  }
}
