// angular-frontend/src/app/shared/components/auth-modal/auth-modal.component.ts
import {
  Component, inject, OnInit, OnDestroy, ElementRef, ViewChild, AfterViewInit
} from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  ReactiveFormsModule, FormsModule,
  FormBuilder, Validators, AbstractControl, ValidationErrors
} from '@angular/forms';
import { Router } from '@angular/router';
import { Subscription } from 'rxjs';
import { AuthService } from '../../../core/services/auth.service';
import { AuthModalService, AuthModalState, AuthModalTab } from '../../services/auth-modal.service';
import { environment } from '../../../../environments/environment';

declare const google: any;

/**
 * AuthModalComponent
 *
 * A full-featured inline dialog with Login / Register tabs.
 * Triggered by AuthModalService.open(). Sits in AppComponent's template
 * so it is available on every page without routing.
 *
 * Features:
 *   - Animated tab switcher (Login ↔ Register)
 *   - Login: email/password + forgot-password flow + Google OAuth
 *   - Register: multi-role (jobseeker/recruiter) + Google OAuth
 *   - Closes on backdrop click or × button
 *   - On success: jobseeker → /dashboard, recruiter/admin → React
 */
@Component({
  selector: 'app-auth-modal',
  standalone: true,
  imports: [CommonModule, ReactiveFormsModule, FormsModule],
  templateUrl: './auth-modal.component.html',
  styleUrl: './auth-modal.component.css'
})
export class AuthModalComponent implements OnInit, OnDestroy, AfterViewInit {
  private fb            = inject(FormBuilder);
  private authService   = inject(AuthService);
  private modalService  = inject(AuthModalService);
  private router        = inject(Router);

  @ViewChild('loginGoogleBtn')    loginGoogleBtnRef!:    ElementRef;
  @ViewChild('registerGoogleBtn') registerGoogleBtnRef!: ElementRef;

  // ── Modal State ──
  state: AuthModalState = { open: false, tab: 'login' };
  private subs = new Subscription();
  private googleScriptLoaded = false;

  // ── Login State ──
  loginLoading       = false;
  loginError         = '';
  showLoginPassword  = false;
  showForgot         = false;
  forgotEmail        = '';
  forgotLoading      = false;
  forgotMessage      = '';
  forgotError        = '';

  loginForm = this.fb.group({
    email:    ['', [Validators.required, Validators.email]],
    password: ['', Validators.required]
  });

  // ── Register State ──
  registerLoading    = false;
  registerError      = '';
  showRegPwd         = false;
  showRegConfirmPwd  = false;

  registerForm = this.fb.group({
    name:            ['', Validators.required],
    email:           ['', [Validators.required, Validators.email]],
    role:            ['jobseeker', Validators.required],
    companyName:     [''],
    companyWebsite:  [''],
    password:        ['', [Validators.required, Validators.minLength(6)]],
    confirmPassword: ['', Validators.required]
  }, { validators: this.passwordMatchValidator });

  get isRecruiter(): boolean {
    return this.registerForm.get('role')?.value === 'recruiter';
  }

  passwordMatchValidator(ctrl: AbstractControl): ValidationErrors | null {
    const pw  = ctrl.get('password');
    const cpw = ctrl.get('confirmPassword');
    if (pw && cpw && pw.value !== cpw.value) {
      cpw.setErrors({ passwordMismatch: true });
      return { passwordMismatch: true };
    }
    return null;
  }

  hasRegError(field: string, error: string): boolean {
    const c = this.registerForm.get(field);
    return !!(c?.hasError(error) && c?.touched);
  }

  // ── Tab indicator position ──
  get tabTranslate(): string {
    return this.state.tab === 'register' ? 'translateX(100%)' : 'translateX(0)';
  }

  ngOnInit(): void {
    // Subscribe to modal open/close/tab changes
    this.subs.add(
      this.modalService.state.subscribe(s => {
        const wasOpen = this.state.open;
        this.state = s;

        if (s.open && !wasOpen) {
          // Reset forms when freshly opened
          this.resetForms();
          // Pre-fill role if provided
          if (s.role) {
            this.registerForm.patchValue({ role: s.role });
          }
          // Prevent body scroll
          document.body.style.overflow = 'hidden';
        }

        if (!s.open && wasOpen) {
          document.body.style.overflow = '';
        }

        // Re-render Google button after tab change (needs container in DOM)
        if (s.open) {
          setTimeout(() => this.renderGoogleButtons(), 50);
        }
      })
    );

    // Role watcher for recruiter fields
    this.registerForm.get('role')?.valueChanges.subscribe(role => {
      const cn = this.registerForm.get('companyName');
      if (role === 'recruiter') {
        cn?.setValidators(Validators.required);
      } else {
        cn?.clearValidators();
      }
      cn?.updateValueAndValidity();
    });
  }

  ngAfterViewInit(): void {
    this.loadGoogleScript();
  }

  ngOnDestroy(): void {
    this.subs.unsubscribe();
    document.body.style.overflow = '';
  }

  // ── Google Script ──
  private loadGoogleScript(): void {
    if (this.googleScriptLoaded || document.querySelector('script[src*="accounts.google.com/gsi"]')) {
      this.googleScriptLoaded = true;
      return;
    }
    const s = document.createElement('script');
    s.src = 'https://accounts.google.com/gsi/client';
    s.async = true;
    s.defer = true;
    s.onload = () => {
      this.googleScriptLoaded = true;
      this.renderGoogleButtons();
    };
    document.head.appendChild(s);
  }

  private renderGoogleButtons(): void {
    if (typeof google === 'undefined' || !this.state.open) return;

    google.accounts.id.initialize({
      client_id: environment.googleClientId,
      callback: (response: any) => this.handleGoogleSuccess(response.credential)
    });

    const loginBtn = document.getElementById('modal-google-login-btn');
    if (loginBtn && this.state.tab === 'login') {
      loginBtn.innerHTML = '';
      google.accounts.id.renderButton(loginBtn, {
        theme: 'outline', size: 'large', width: '100%',
        text: 'signin_with', shape: 'rectangular'
      });
    }

    const regBtn = document.getElementById('modal-google-register-btn');
    if (regBtn && this.state.tab === 'register') {
      regBtn.innerHTML = '';
      google.accounts.id.renderButton(regBtn, {
        theme: 'outline', size: 'large', width: '100%',
        text: 'signup_with', shape: 'rectangular'
      });
    }
  }

  // ── Public ──
  close(): void   { this.modalService.close(); }
  switchTab(tab: AuthModalTab): void {
    this.modalService.switchTab(tab);
    setTimeout(() => this.renderGoogleButtons(), 80);
  }

  onBackdropClick(e: MouseEvent): void {
    if ((e.target as HTMLElement).classList.contains('modal-overlay')) {
      this.close();
    }
  }

  // ── Login ──
  onLoginSubmit(): void {
    if (this.loginForm.invalid) return;
    this.loginLoading = true;
    this.loginError   = '';
    const { email, password } = this.loginForm.value;
    this.authService.login(email!, password!).subscribe({
      next: res  => this.handleSuccess(res.user.role),
      error: err => {
        this.loginError   = err.error?.message || 'Login failed. Please try again.';
        this.loginLoading = false;
      }
    });
  }

  submitForgotPassword(): void {
    if (!this.forgotEmail.trim()) { this.forgotError = 'Please enter your email.'; return; }
    this.forgotLoading = true;
    this.forgotError   = '';
    this.forgotMessage = '';
    this.authService.forgotPassword(this.forgotEmail.trim()).subscribe({
      next: res  => { this.forgotMessage = res.message; this.forgotLoading = false; },
      error: err => {
        this.forgotError   = err.error?.message || 'Failed to send reset email.';
        this.forgotLoading = false;
      }
    });
  }

  showForgotView():   void { this.showForgot = true;  this.forgotEmail = ''; this.forgotMessage = ''; this.forgotError = ''; }
  hideForgotView():   void { this.showForgot = false; }
  toggleLoginPwd():   void { this.showLoginPassword = !this.showLoginPassword; }
  toggleRegPwd():     void { this.showRegPwd = !this.showRegPwd; }
  toggleRegConfirm(): void { this.showRegConfirmPwd = !this.showRegConfirmPwd; }

  // ── Register ──
  onRegisterSubmit(): void {
    if (this.registerForm.invalid) { this.registerForm.markAllAsTouched(); return; }
    this.registerLoading = true;
    this.registerError   = '';
    const v = this.registerForm.value;
    const payload: any = {
      name:     v.name!.trim(),
      email:    v.email!.trim(),
      password: v.password!,
      role:     v.role!
    };
    if (v.role === 'recruiter') {
      payload.companyName    = v.companyName?.trim();
      payload.companyWebsite = v.companyWebsite?.trim();
    }
    this.authService.register(payload).subscribe({
      next: res  => this.handleSuccess(res.user.role),
      error: err => {
        this.registerError   = err.error?.message || 'Registration failed.';
        this.registerLoading = false;
      }
    });
  }

  // ── Google OAuth (shared) ──
  handleGoogleSuccess(credential: string): void {
    const role = this.state.tab === 'register'
      ? (this.registerForm.get('role')?.value || 'jobseeker')
      : 'jobseeker';
    this.loginLoading    = true;
    this.registerLoading = true;
    this.authService.googleLogin(credential, role).subscribe({
      next: res  => this.handleSuccess(res.user.role),
      error: err => {
        const msg = err.error?.message || 'Google authentication failed.';
        this.loginError      = msg;
        this.registerError   = msg;
        this.loginLoading    = false;
        this.registerLoading = false;
      }
    });
  }

  // ── Post-auth redirect ──
  private handleSuccess(role: string): void {
    this.close();
    const dest = this.authService.getDashboardRoute(role);
    this.router.navigate([dest.path]);
  }

  private resetForms(): void {
    this.loginForm.reset();
    this.registerForm.reset({ role: 'jobseeker' });
    this.loginError = '';
    this.registerError = '';
    this.loginLoading  = false;
    this.registerLoading = false;
    this.showForgot    = false;
    this.showLoginPassword = false;
    this.showRegPwd    = false;
    this.showRegConfirmPwd = false;
  }
}

<div class="modal-overlay" *ngIf="state.open" (click)="onBackdropClick($event)">
  <div class="modal-container animate-scale-in" (click)="$event.stopPropagation()">
    <button class="modal-close" (click)="close()">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
        <line x1="18" y1="6" x2="6" y2="18"></line>
        <line x1="6" y1="6" x2="18" y2="18"></line>
      </svg>
    </button>

    <!-- Header -->
    <div class="modal-header">
      <h2 class="modal-title">
        {{ state.tab === 'login' ? (showForgot ? 'Reset Password' : 'Welcome back') : 'Create an account' }}
      </h2>
      <p class="modal-subtitle" *ngIf="state.tab === 'login' && !showForgot">Sign in to your TalentBridge account</p>
      <p class="modal-subtitle" *ngIf="state.tab === 'login' && showForgot">We'll help you get back in</p>
      <p class="modal-subtitle" *ngIf="state.tab === 'register'">Join TalentBridge today</p>
    </div>

    <!-- Tab Switcher (hide if forgot password view is active) -->
    <div class="tab-switcher" *ngIf="!showForgot">
      <div class="tab-indicator" [style.transform]="tabTranslate"></div>
      <button class="tab-btn" [class.active]="state.tab === 'login'" (click)="switchTab('login')">Login</button>
      <button class="tab-btn" [class.active]="state.tab === 'register'" (click)="switchTab('register')">Register</button>
    </div>

    <!-- ═══ LOGIN TAB ═══ -->
    <div class="auth-view" [hidden]="state.tab !== 'login'">
      
      <!-- Forgot Password View -->
      <ng-container *ngIf="showForgot; else loginFormTpl">
        <div class="auth-form-container">
          <div class="error-banner" *ngIf="forgotError">
            <span>{{ forgotError }}</span>
          </div>
          <div class="success-banner" *ngIf="forgotMessage" style="color:var(--success-500); margin-bottom:1rem; font-size:14px;">
            <span>{{ forgotMessage }}</span>
          </div>

          <div class="input-group" style="margin-bottom:1rem;">
            <svg class="input-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>
            <input type="email" class="auth-input" placeholder="Enter your email address" [(ngModel)]="forgotEmail">
          </div>
          
          <button class="btn-primary" style="width:100%; margin-bottom:0.5rem;" (click)="submitForgotPassword()" [disabled]="forgotLoading">
            <span *ngIf="forgotLoading" class="spinner"></span>
            {{ forgotLoading ? 'Sending…' : 'Send Reset Link' }}
          </button>
          <button class="btn-ghost" style="width:100%; justify-content:center;" (click)="hideForgotView()">
            ← Back to login
          </button>
        </div>
      </ng-container>

      <ng-template #loginFormTpl>
        <div class="error-banner" *ngIf="loginError">
          <span>{{ loginError }}</span>
        </div>

        <form [formGroup]="loginForm" (ngSubmit)="onLoginSubmit()" class="auth-form">
          <div class="input-group">
            <svg class="input-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>
            <input formControlName="email" type="email" class="auth-input" placeholder="Email address">
          </div>
          <div class="input-group">
            <svg class="input-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
            <input formControlName="password" [type]="showLoginPassword ? 'text' : 'password'" class="auth-input" placeholder="Password">
            <button type="button" class="password-toggle" (click)="toggleLoginPwd()">
              <svg *ngIf="!showLoginPassword" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>
              <svg *ngIf="showLoginPassword" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"/><line x1="1" y1="1" x2="23" y2="23"/></svg>
            </button>
          </div>
          
          <button type="button" class="forgot-link" (click)="showForgotView()">Forgot password?</button>
          
          <button type="submit" class="btn-primary" style="width:100%" [disabled]="loginForm.invalid || loginLoading">
            <span *ngIf="loginLoading" class="spinner"></span>
            {{ loginLoading ? 'Signing in…' : 'Sign In' }}
          </button>
        </form>

        <div class="divider"><span>or</span></div>
        <div id="modal-google-login-btn"></div>
      </ng-template>
    </div>

    <!-- ═══ REGISTER TAB ═══ -->
    <div class="auth-view" [hidden]="state.tab !== 'register'">
      <div class="error-banner" *ngIf="registerError">
        <span>{{ registerError }}</span>
      </div>

      <form [formGroup]="registerForm" (ngSubmit)="onRegisterSubmit()" class="auth-form">
        <!-- Role Selector -->
        <div class="role-selector">
          <label class="role-option" [class.active]="registerForm.get('role')?.value === 'jobseeker'">
            <input type="radio" formControlName="role" value="jobseeker">
            Job Seeker
          </label>
          <label class="role-option" [class.active]="registerForm.get('role')?.value === 'recruiter'">
            <input type="radio" formControlName="role" value="recruiter">
            Recruiter
          </label>
        </div>

        <div class="input-group">
          <svg class="input-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>
          <input formControlName="name" type="text" class="auth-input" [class.input-error]="hasRegError('name', 'required')" placeholder="Full name">
        </div>

        <div class="input-group">
          <svg class="input-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="4" width="20" height="16" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>
          <input formControlName="email" type="email" class="auth-input" [class.input-error]="hasRegError('email', 'required') || hasRegError('email', 'email')" placeholder="Email address">
        </div>

        <ng-container *ngIf="isRecruiter">
          <div class="input-group">
            <svg class="input-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="7" width="20" height="14" rx="2" ry="2"/><path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"/></svg>
            <input formControlName="companyName" type="text" class="auth-input" [class.input-error]="hasRegError('companyName', 'required')" placeholder="Company name">
          </div>
          <div class="input-group">
            <svg class="input-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>
            <input formControlName="companyWebsite" type="url" class="auth-input" placeholder="Company website (optional)">
          </div>
        </ng-container>

        <div class="input-group">
          <svg class="input-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
          <input formControlName="password" [type]="showRegPwd ? 'text' : 'password'" class="auth-input" [class.input-error]="hasRegError('password', 'required') || hasRegError('password', 'minlength')" placeholder="Password (min 6 chars)">
          <button type="button" class="password-toggle" (click)="toggleRegPwd()">
             <svg *ngIf="!showRegPwd" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>
             <svg *ngIf="showRegPwd" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"/><line x1="1" y1="1" x2="23" y2="23"/></svg>
          </button>
        </div>

        <div class="input-group">
          <svg class="input-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
          <input formControlName="confirmPassword" [type]="showRegConfirmPwd ? 'text' : 'password'" class="auth-input" [class.input-error]="hasRegError('confirmPassword', 'required') || registerForm.get('confirmPassword')?.hasError('passwordMismatch')" placeholder="Confirm password">
        </div>

        <button type="submit" class="btn-primary" style="width:100%" [disabled]="registerForm.invalid || registerLoading">
          <span *ngIf="registerLoading" class="spinner"></span>
          {{ registerLoading ? 'Creating account…' : 'Create Account' }}
        </button>
      </form>

      <div class="divider"><span>or</span></div>
      <div id="modal-google-register-btn"></div>
    </div>

  </div>
</div>

// frontend/src/components/AuthModal.jsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import GoogleLoginBtn from "./GoogleLoginBtn";
import ForgotPassword from "./ForgotPassword";
import {
  X,
  Mail,
  Lock,
  User,
  Eye,
  EyeOff,
  Loader2,
  AlertCircle,
} from "lucide-react";
import toast from "react-hot-toast";
import "./AuthModal.css";

/**
 * Authentication Modal Component
 * Supports Login, Register, and Forgot Password views
 * Receives the selected role from the HomePage role card click
 *
 * @param {Object} props
 * @param {boolean} props.isOpen - Whether the modal is visible
 * @param {Function} props.onClose - Callback to close the modal
 * @param {string} props.role - Pre-selected role ("jobseeker" or "recruiter")
 */
const AuthModal = ({ isOpen, onClose, role }) => {
  const [activeTab, setActiveTab] = useState("login");
  const [showForgotPassword, setShowForgotPassword] = useState(false);
  const [showPassword, setShowPassword] = useState(false);
  const [showConfirmPassword, setShowConfirmPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [errors, setErrors] = useState({});

  // Form state
  const [loginData, setLoginData] = useState({ email: "", password: "" });
  const [registerData, setRegisterData] = useState({
    name: "",
    email: "",
    password: "",
    confirmPassword: "",
  });

  const { login, register, googleLogin } = useAuth();
  const navigate = useNavigate();

  if (!isOpen) return null;

  const roleLabel = role === "recruiter" ? "Recruiter" : "Job Seeker";

  /**
   * Redirect user to their role-specific dashboard after auth
   */
  const redirectToDashboard = (userRole) => {
    const routes = {
      jobseeker: "/jobseeker/dashboard",
      recruiter: "/recruiter/dashboard",
      admin: "/admin/dashboard",
    };
    navigate(routes[userRole] || "/");
    onClose();
  };

  /**
   * Handle Login form submission
   */
  const handleLogin = async (e) => {
    e.preventDefault();
    setErrors({});

    if (!loginData.email || !loginData.password) {
      setErrors({ general: "Please fill in all fields" });
      return;
    }

    try {
      setLoading(true);
      const data = await login(loginData.email, loginData.password);
      toast.success(data.message || "Login successful!");
      redirectToDashboard(data.user.role);
    } catch (error) {
      const message =
        error.response?.data?.message || "Login failed. Please try again.";
      setErrors({ general: message });
      toast.error(message);
    } finally {
      setLoading(false);
    }
  };

  /**
   * Handle Register form submission
   */
  const handleRegister = async (e) => {
    e.preventDefault();
    setErrors({});

    // Client-side validation
    const newErrors = {};
    if (!registerData.name.trim()) newErrors.name = "Name is required";
    if (!registerData.email.trim()) newErrors.email = "Email is required";
    if (!registerData.password) newErrors.password = "Password is required";
    if (registerData.password.length < 6)
      newErrors.password = "Password must be at least 6 characters";
    if (registerData.password !== registerData.confirmPassword)
      newErrors.confirmPassword = "Passwords do not match";

    if (Object.keys(newErrors).length > 0) {
      setErrors(newErrors);
      return;
    }

    try {
      setLoading(true);
      const data = await register({
        name: registerData.name.trim(),
        email: registerData.email.trim(),
        password: registerData.password,
        role: role || "jobseeker",
      });
      toast.success(data.message || "Registration successful!");
      redirectToDashboard(data.user.role);
    } catch (error) {
      const message =
        error.response?.data?.message || "Registration failed. Please try again.";
      setErrors({ general: message });
      toast.error(message);
    } finally {
      setLoading(false);
    }
  };

  /**
   * Handle Google OAuth success
   */
  const handleGoogleSuccess = async (credential) => {
    try {
      setLoading(true);
      const data = await googleLogin(credential, role);
      toast.success(data.message || "Login successful!");
      redirectToDashboard(data.user.role);
    } catch (error) {
      const message =
        error.response?.data?.message || "Google authentication failed.";
      toast.error(message);
    } finally {
      setLoading(false);
    }
  };

  /**
   * Reset form state when switching tabs
   */
  const switchTab = (tab) => {
    setActiveTab(tab);
    setErrors({});
    setShowPassword(false);
    setShowConfirmPassword(false);
    setShowForgotPassword(false);
  };

  return (
    <div className="modal-overlay" onClick={onClose} id="auth-modal-overlay">
      <div
        className="modal-container glass-strong animate-scale-in"
        onClick={(e) => e.stopPropagation()}
        id="auth-modal"
      >
        {/* Close button */}
        <button className="modal-close" onClick={onClose} id="modal-close-btn">
          <X size={20} />
        </button>

        {/* Modal Header */}
        <div className="modal-header">
          <div className="modal-role-badge">
            <span>{roleLabel}</span>
          </div>
          <h2 className="modal-title">
            {showForgotPassword
              ? "Reset Password"
              : activeTab === "login"
              ? "Welcome Back"
              : "Create Account"}
          </h2>
          <p className="modal-subtitle">
            {showForgotPassword
              ? "We'll help you get back in"
              : activeTab === "login"
              ? `Sign in to your ${roleLabel} account`
              : `Join as a ${roleLabel}`}
          </p>
        </div>

        {/* Forgot Password View */}
        {showForgotPassword ? (
          <ForgotPassword onBack={() => setShowForgotPassword(false)} />
        ) : (
          <>
            {/* Tab Switcher */}
            <div className="tab-switcher" id="auth-tabs">
              <button
                className={`tab-btn ${activeTab === "login" ? "active" : ""}`}
                onClick={() => switchTab("login")}
                id="tab-login"
              >
                Login
              </button>
              <button
                className={`tab-btn ${activeTab === "register" ? "active" : ""}`}
                onClick={() => switchTab("register")}
                id="tab-register"
              >
                Register
              </button>
              <div
                className="tab-indicator"
                style={{
                  transform: `translateX(${activeTab === "login" ? "0" : "100%"})`,
                }}
              />
            </div>

            {/* Error Display */}
            {errors.general && (
              <div className="error-banner" id="auth-error-banner">
                <AlertCircle size={16} />
                <span>{errors.general}</span>
              </div>
            )}

            {/* Login Form */}
            {activeTab === "login" && (
              <form onSubmit={handleLogin} className="auth-form" id="login-form">
                <div className="input-group">
                  <Mail size={18} className="input-icon" />
                  <input
                    type="email"
                    placeholder="Email address"
                    value={loginData.email}
                    onChange={(e) =>
                      setLoginData({ ...loginData, email: e.target.value })
                    }
                    className="auth-input"
                    required
                    id="login-email"
                  />
                </div>

                <div className="input-group">
                  <Lock size={18} className="input-icon" />
                  <input
                    type={showPassword ? "text" : "password"}
                    placeholder="Password"
                    value={loginData.password}
                    onChange={(e) =>
                      setLoginData({ ...loginData, password: e.target.value })
                    }
                    className="auth-input"
                    required
                    id="login-password"
                  />
                  <button
                    type="button"
                    className="password-toggle"
                    onClick={() => setShowPassword(!showPassword)}
                    id="login-toggle-password"
                  >
                    {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                  </button>
                </div>

                <button
                  type="button"
                  className="forgot-link"
                  onClick={() => setShowForgotPassword(true)}
                  id="forgot-password-link"
                >
                  Forgot Password?
                </button>

                <button
                  type="submit"
                  className="btn-primary"
                  disabled={loading}
                  id="login-submit-btn"
                >
                  {loading ? (
                    <>
                      <Loader2 size={18} className="spin" />
                      Signing in...
                    </>
                  ) : (
                    "Sign In"
                  )}
                </button>
              </form>
            )}

            {/* Register Form */}
            {activeTab === "register" && (
              <form onSubmit={handleRegister} className="auth-form" id="register-form">
                <div className="input-group">
                  <User size={18} className="input-icon" />
                  <input
                    type="text"
                    placeholder="Full name"
                    value={registerData.name}
                    onChange={(e) =>
                      setRegisterData({ ...registerData, name: e.target.value })
                    }
                    className={`auth-input ${errors.name ? "input-error" : ""}`}
                    required
                    id="register-name"
                  />
                </div>
                {errors.name && (
                  <span className="field-error">{errors.name}</span>
                )}

                <div className="input-group">
                  <Mail size={18} className="input-icon" />
                  <input
                    type="email"
                    placeholder="Email address"
                    value={registerData.email}
                    onChange={(e) =>
                      setRegisterData({ ...registerData, email: e.target.value })
                    }
                    className={`auth-input ${errors.email ? "input-error" : ""}`}
                    required
                    id="register-email"
                  />
                </div>
                {errors.email && (
                  <span className="field-error">{errors.email}</span>
                )}

                <div className="input-group">
                  <Lock size={18} className="input-icon" />
                  <input
                    type={showPassword ? "text" : "password"}
                    placeholder="Password (min. 6 characters)"
                    value={registerData.password}
                    onChange={(e) =>
                      setRegisterData({
                        ...registerData,
                        password: e.target.value,
                      })
                    }
                    className={`auth-input ${errors.password ? "input-error" : ""}`}
                    required
                    id="register-password"
                  />
                  <button
                    type="button"
                    className="password-toggle"
                    onClick={() => setShowPassword(!showPassword)}
                    id="register-toggle-password"
                  >
                    {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
                  </button>
                </div>
                {errors.password && (
                  <span className="field-error">{errors.password}</span>
                )}

                <div className="input-group">
                  <Lock size={18} className="input-icon" />
                  <input
                    type={showConfirmPassword ? "text" : "password"}
                    placeholder="Confirm password"
                    value={registerData.confirmPassword}
                    onChange={(e) =>
                      setRegisterData({
                        ...registerData,
                        confirmPassword: e.target.value,
                      })
                    }
                    className={`auth-input ${
                      errors.confirmPassword ? "input-error" : ""
                    }`}
                    required
                    id="register-confirm-password"
                  />
                  <button
                    type="button"
                    className="password-toggle"
                    onClick={() => setShowConfirmPassword(!showConfirmPassword)}
                    id="register-toggle-confirm"
                  >
                    {showConfirmPassword ? (
                      <EyeOff size={18} />
                    ) : (
                      <Eye size={18} />
                    )}
                  </button>
                </div>
                {errors.confirmPassword && (
                  <span className="field-error">{errors.confirmPassword}</span>
                )}

                <button
                  type="submit"
                  className="btn-primary"
                  disabled={loading}
                  id="register-submit-btn"
                >
                  {loading ? (
                    <>
                      <Loader2 size={18} className="spin" />
                      Creating Account...
                    </>
                  ) : (
                    "Create Account"
                  )}
                </button>
              </form>
            )}

            {/* Divider */}
            <div className="divider">
              <span>or continue with</span>
            </div>

            {/* Google OAuth */}
            <GoogleLoginBtn
              onSuccess={handleGoogleSuccess}
              text={activeTab === "login" ? "signin_with" : "signup_with"}
            />
          </>
        )}
      </div>
    </div>
  );
};

export default AuthModal;
