// angular-frontend/src/app/features/recruiter/dashboard/recruiter-dashboard.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { JobService, Job } from '../../../core/services/job.service';
import { VerificationPanelComponent } from '../components/verification-panel/verification-panel.component';
import { JobFormComponent } from '../components/job-form/job-form.component';
import { ManageApplicationsComponent } from '../components/manage-applications/manage-applications.component';

@Component({
  selector: 'app-recruiter-dashboard',
  standalone: true,
  imports: [
    CommonModule,
    VerificationPanelComponent,
    JobFormComponent,
    ManageApplicationsComponent
  ],
  templateUrl: './recruiter-dashboard.component.html',
  styleUrls: ['./recruiter-dashboard.component.css']
})
export class RecruiterDashboardComponent implements OnInit {
  authService = inject(AuthService);
  jobService = inject(JobService);
  router = inject(Router);

  user = this.authService.currentUser;
  jobs: Job[] = [];
  loading = true;

  verifStatus = 'none';
  verifRequired = false;

  isJobFormOpen = false;
  editingJob: Job | null = null;
  
  isAppsOpen = false;
  selectedJobForApps: Job | null = null;

  ngOnInit() {
    this.fetchJobs();
  }

  fetchJobs() {
    this.loading = true;
    this.jobService.getMyJobs().subscribe({
      next: (res) => {
        this.jobs = res.data || [];
        this.loading = false;
      },
      error: (err) => {
        console.error('Failed to load jobs', err);
        this.loading = false;
      }
    });
  }

  logout() {
    this.authService.logout().subscribe(() => {
      this.router.navigate(['/']);
    });
  }

  handleVerifStatusChange(data: any) {
    this.verifStatus = data.companyVerificationStatus;
    this.verifRequired = data.verificationRequired;
  }

  get canPost(): boolean {
    return !this.verifRequired || this.verifStatus === 'approved';
  }

  openCreateJob() {
    if (this.verifRequired && this.verifStatus !== 'approved') {
      alert('Company verification required. Please submit your company details below.');
      return;
    }
    this.editingJob = null;
    this.isJobFormOpen = true;
  }

  openEditJob(job: Job) {
    this.editingJob = job;
    this.isJobFormOpen = true;
  }

  openManageApps(job: Job) {
    this.selectedJobForApps = job;
    this.isAppsOpen = true;
  }

  handleDeleteJob(id: string) {
    if (confirm('Are you sure you want to delete this job? All applications will also be deleted.')) {
      this.jobService.deleteJob(id).subscribe({
        next: () => {
          this.fetchJobs();
        },
        error: (err) => {
          console.error('Failed to delete job', err);
        }
      });
    }
  }

  onJobFormClosed() {
    this.isJobFormOpen = false;
    this.editingJob = null;
  }

  onJobSaved() {
    this.isJobFormOpen = false;
    this.editingJob = null;
    this.fetchJobs();
  }

  onAppsClosed() {
    this.isAppsOpen = false;
    this.selectedJobForApps = null;
  }
}

<!-- ═══════════════════════ RECRUITER DASHBOARD ═══════════════════════ -->
<div class="dashboard-page">

  <!-- ── Sticky Header ── -->
  <header class="dashboard-header">
    <a class="dashboard-logo" (click)="router.navigate(['/'])">
      <div class="dashboard-logo-icon"></div>
      <span class="dashboard-logo-text">TalentBridge</span>
    </a>
    <div class="dashboard-header-actions">
      <button class="btn-logout-sm" (click)="logout()">Logout</button>
    </div>
  </header>

  <!-- ── Main Content ── -->
  <main class="dashboard-main">

    <!-- Welcome Banner -->
    <div class="welcome-banner" *ngIf="user">
      <div class="welcome-bg-glow"></div>
      <div class="welcome-text">
        <p class="welcome-greeting">Good afternoon</p>
        <h1 class="welcome-name">Welcome back, {{ user?.name }}!</h1>
        <p class="welcome-sub">Here's your recruiting activity overview.</p>
      </div>
      <div class="welcome-badge-area">
        <div class="welcome-role-badge">
          <p class="welcome-role-label">Recruiter</p>
        </div>
        <div class="welcome-role-badge verified-badge" *ngIf="verifStatus === 'approved'">
          <p class="welcome-role-label">Verified</p>
        </div>
      </div>
    </div>

    <!-- Verification Panel Component -->
    <app-verification-panel (statusChange)="handleVerifStatusChange($event)"></app-verification-panel>

    <!-- Stats Grid -->
    <div class="stats-grid">
      <div class="stat-card">
        <div class="stat-card-icon"></div>
        <div class="stat-card-info">
          <span class="stat-card-value">{{ jobs.length }}</span>
          <span class="stat-card-label">Active Jobs</span>
        </div>
      </div>
      <div class="stat-card">
        <div class="stat-card-icon"></div>
        <div class="stat-card-info">
          <span class="stat-card-value">--</span>
          <span class="stat-card-label">Total Applicants</span>
        </div>
      </div>
      <div class="stat-card">
        <div class="stat-card-icon"></div>
        <div class="stat-card-info">
          <span class="stat-card-value">--</span>
          <span class="stat-card-label">Shortlisted</span>
        </div>
      </div>
      <div class="stat-card">
        <div class="stat-card-icon"></div>
        <div class="stat-card-info">
          <span class="stat-card-value">--</span>
          <span class="stat-card-label">Profile Views</span>
        </div>
      </div>
    </div>

    <!-- Job Postings -->
    <div class="jobs-section">
      <div class="jobs-header">
        <h3 class="jobs-title">My Job Postings</h3>
        <div class="jobs-header-actions">
          <span class="verif-warning" *ngIf="verifRequired && verifStatus !== 'approved'">
            ⚠ Verification required to post
          </span>
          <button class="btn-post-job" [disabled]="!canPost" (click)="openCreateJob()">
            + Post a Job
          </button>
        </div>
      </div>

      <div class="jobs-content">
        <div *ngIf="loading" class="loading-state">Loading jobs...</div>
        
        <div *ngIf="!loading && jobs.length === 0" class="empty-state">
          <div class="empty-icon"></div>
          <p>No jobs posted yet</p>
          <span>Click "Post a Job" to start receiving applications.</span>
        </div>

        <div *ngIf="!loading && jobs.length > 0" class="job-list">
          <div class="job-card" *ngFor="let job of jobs">
            <div class="job-info">
              <h4 class="job-title">{{ job.title }}</h4>
              <p class="job-meta">
                {{ job.company }} • {{ job.location || 'Location not specified' }} • Posted {{ job.createdAt | date:'d MMM y' }}
              </p>
              <div class="job-skills">
                <span class="skill-badge" *ngFor="let skill of job.requiredSkills?.slice(0, 3)">{{ skill }}</span>
                <span class="skill-badge" *ngIf="job.requiredSkills && job.requiredSkills.length > 3">
                  +{{ job.requiredSkills.length - 3 }} more
                </span>
              </div>
            </div>
            <div class="job-actions">
              <button class="btn-manage-apps" (click)="openManageApps(job)">
                Applications
              </button>
              <button class="btn-edit" (click)="openEditJob(job)">Edit</button>
              <button class="btn-delete" (click)="handleDeleteJob(job._id)">Delete</button>
            </div>
          </div>
        </div>
      </div>
    </div>

  </main>
</div>

<!-- Modals -->
<app-job-form
  *ngIf="isJobFormOpen"
  [jobData]="editingJob"
  (closeModal)="onJobFormClosed()"
  (saved)="onJobSaved()">
</app-job-form>

<app-manage-applications
  *ngIf="isAppsOpen && selectedJobForApps"
  [job]="selectedJobForApps"
  (closeModal)="onAppsClosed()">
</app-manage-applications>

// react-frontend/src/pages/RecruiterDashboard.jsx
import { useState, useEffect } from "react";
import { useAuth } from "../context/AuthContext";
import { useNavigate } from "react-router-dom";
import toast from "react-hot-toast";
import {
  Users,
  Briefcase,
  Eye,
  UserCheck,
  Plus,
  Edit2,
  Trash2,
  LogOut,
  ShieldCheck,
} from "lucide-react";
import { getMyJobs, createJob, updateJob, deleteJob } from "../api/jobApi";
import JobForm from "../components/recruiter/JobForm";
import ManageApplications from "../components/recruiter/ManageApplications";
import RecruiterVerificationPanel from "../components/recruiter/RecruiterVerificationPanel";

/**
 * Recruiter Dashboard
 * Displays welcome message, hiring stats, job management, and company verification panel.
 */
const RecruiterDashboard = () => {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const [jobs, setJobs] = useState([]);
  const [loading, setLoading] = useState(true);

  // Verification state (driven by the panel's callback)
  const [verifStatus, setVerifStatus] = useState("none");
  const [verifRequired, setVerifRequired] = useState(false);

  // Modals
  const [isJobFormOpen, setIsJobFormOpen] = useState(false);
  const [editingJob, setEditingJob] = useState(null);
  const [isAppsOpen, setIsAppsOpen] = useState(false);
  const [selectedJobForApps, setSelectedJobForApps] = useState(null);

  useEffect(() => {
    fetchJobs();
  }, []);

  const fetchJobs = async () => {
    try {
      setLoading(true);
      const res = await getMyJobs();
      setJobs(res.data.data);
    } catch (err) {
      toast.error("Failed to load your jobs");
    } finally {
      setLoading(false);
    }
  };

  const handleCreateOrUpdateJob = async (jobData, id) => {
    if (id) {
      await updateJob(id, jobData);
      toast.success("Job updated successfully");
    } else {
      await createJob(jobData);
      toast.success("Job posted successfully");
    }
    fetchJobs();
  };

  const handleDeleteJob = async (id) => {
    if (window.confirm("Are you sure you want to delete this job? All applications will also be deleted.")) {
      try {
        await deleteJob(id);
        toast.success("Job deleted");
        fetchJobs();
      } catch (err) {
        toast.error("Failed to delete job");
      }
    }
  };

  const openEditJob = (job) => { setEditingJob(job); setIsJobFormOpen(true); };
  const openCreateJob = () => {
    // Block if verification required and not approved
    if (verifRequired && verifStatus !== "approved") {
      toast.error("Company verification required. Please submit your company details below.");
      return;
    }
    setEditingJob(null);
    setIsJobFormOpen(true);
  };
  const openManageApps = (job) => { setSelectedJobForApps(job); setIsAppsOpen(true); };

  const handleLogout = async () => {
    try {
      await logout();
      toast.success("Logged out successfully");
      navigate("/");
    } catch (err) {
      toast.error("Failed to logout");
    }
  };

  // Called by the verification panel when status changes
  const handleVerifStatusChange = (data) => {
    setVerifStatus(data.companyVerificationStatus);
    setVerifRequired(data.verificationRequired);
  };

  const canPost = !verifRequired || verifStatus === "approved";

  return (
    <div className="dashboard-page">
      <div className="dashboard-container">

        {/* Welcome Section */}
        <div className="welcome-section animate-fade-in-up">
          <div className="welcome-text">
            <h1>
              Welcome back, <span className="gradient-text-recruiter">{user?.name}</span>
            </h1>
            <p>Here's your recruiting activity overview.</p>
          </div>
          <div className="welcome-actions">
            <div className="welcome-badge role-recruiter">
              <Users size={16} />
              Recruiter
            </div>
            {verifStatus === "approved" && (
              <div className="verif-badge-approved">
                <ShieldCheck size={14} /> Verified
              </div>
            )}
            <button className="btn-logout" onClick={handleLogout} title="Logout">
              <LogOut size={16} />
              Logout
            </button>
          </div>
        </div>

        {/* Verification Panel */}
        <RecruiterVerificationPanel onStatusChange={handleVerifStatusChange} />

        {/* Stats Grid */}
        <div className="stats-grid">
          <div className="stat-card glass" style={{ animationDelay: "0.1s" }}>
            <div className="stat-card-icon icon-purple">
              <Briefcase size={22} />
            </div>
            <div className="stat-card-info">
              <span className="stat-card-value">{jobs.length}</span>
              <span className="stat-card-label">Active Jobs</span>
            </div>
          </div>
          <div className="stat-card glass" style={{ animationDelay: "0.2s" }}>
            <div className="stat-card-icon icon-blue">
              <Users size={22} />
            </div>
            <div className="stat-card-info">
              <span className="stat-card-value">--</span>
              <span className="stat-card-label">Total Applicants</span>
            </div>
          </div>
          <div className="stat-card glass" style={{ animationDelay: "0.3s" }}>
            <div className="stat-card-icon icon-green">
              <UserCheck size={22} />
            </div>
            <div className="stat-card-info">
              <span className="stat-card-value">--</span>
              <span className="stat-card-label">Shortlisted</span>
            </div>
          </div>
          <div className="stat-card glass" style={{ animationDelay: "0.4s" }}>
            <div className="stat-card-icon icon-amber">
              <Eye size={22} />
            </div>
            <div className="stat-card-info">
              <span className="stat-card-value">--</span>
              <span className="stat-card-label">Profile Views</span>
            </div>
          </div>
        </div>

        {/* Job Postings */}
        <div className="dashboard-grid" style={{ gridTemplateColumns: "1fr", marginTop: "30px" }}>
          <div className="dashboard-card glass animate-fade-in-up">
            <div className="card-header" style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
              <h3>
                <Briefcase size={18} />
                My Job Postings
              </h3>
              <div style={{ display: "flex", alignItems: "center", gap: "10px" }}>
                {verifRequired && verifStatus !== "approved" && (
                  <span style={{ fontSize: "12px", color: "var(--warning-500)", display: "flex", alignItems: "center", gap: "5px" }}>
                    ⚠ Verification required to post
                  </span>
                )}
                <button
                  className="btn-primary"
                  onClick={openCreateJob}
                  disabled={!canPost}
                  style={{ padding: "8px 16px", opacity: canPost ? 1 : 0.5 }}
                  title={canPost ? "Post a new job" : "Company verification required"}
                >
                  <Plus size={16} /> Post a Job
                </button>
              </div>
            </div>

            {loading ? (
              <div style={{ padding: "40px", textAlign: "center" }}>Loading jobs...</div>
            ) : jobs.length === 0 ? (
              <div className="empty-state">
                <Briefcase size={40} className="empty-icon" />
                <p>No jobs posted yet</p>
                <span>Click "Post a Job" to start receiving applications.</span>
              </div>
            ) : (
              <div style={{ display: "flex", flexDirection: "column", gap: "15px", marginTop: "20px" }}>
                {jobs.map((job) => (
                  <div key={job._id} className="job-card">
                    <div className="job-card-info">
                      <h4>{job.title}</h4>
                      <p>
                        {job.company} • {job.location || "Location not specified"} • Posted {new Date(job.createdAt).toLocaleDateString()}
                      </p>
                      <div className="job-card-skills">
                        {job.requiredSkills.slice(0, 3).map((skill, i) => (
                          <span key={i} className="badge badge-navy">{skill}</span>
                        ))}
                        {job.requiredSkills.length > 3 && (
                          <span className="badge badge-navy">+{job.requiredSkills.length - 3} more</span>
                        )}
                      </div>
                    </div>
                    <div className="job-card-actions">
                      <button
                        className="btn-secondary"
                        onClick={() => openManageApps(job)}
                        style={{ padding: "6px 12px", fontSize: "13px" }}
                      >
                        <Users size={16} /> Applications
                      </button>
                      <button className="btn-ghost" onClick={() => openEditJob(job)} title="Edit Job" style={{ padding: "6px" }}>
                        <Edit2 size={16} />
                      </button>
                      <button
                        className="btn-ghost"
                        onClick={() => handleDeleteJob(job._id)}
                        style={{ padding: "6px", color: "var(--error-500)" }}
                        title="Delete Job"
                      >
                        <Trash2 size={16} />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </div>
        </div>
      </div>

      <JobForm
        isOpen={isJobFormOpen}
        onClose={() => setIsJobFormOpen(false)}
        initialData={editingJob}
        onSubmit={handleCreateOrUpdateJob}
      />
      <ManageApplications
        isOpen={isAppsOpen}
        onClose={() => setIsAppsOpen(false)}
        job={selectedJobForApps}
      />
    </div>
  );
};

export default RecruiterDashboard;
