// frontend/src/pages/AdminLogin.jsx
import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { Mail, Lock, Eye, EyeOff, Loader2, Shield, AlertCircle } from "lucide-react";
import toast from "react-hot-toast";

/**
 * Admin Login Page
 * Accessible only at /admin/login
 * - No registration option
 * - No Google OAuth
 * - Minimal, secure design
 */
const AdminLogin = () => {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const [showPassword, setShowPassword] = useState(false);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState("");

  const { login } = useAuth();
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    setError("");

    if (!email || !password) {
      setError("Please fill in all fields");
      return;
    }

    try {
      setLoading(true);
      const data = await login(email, password);

      // Verify the user is actually an admin
      if (data.user.role !== "admin") {
        setError("Access denied. Admin credentials required.");
        toast.error("Access denied. Admin credentials required.");
        return;
      }

      toast.success("Welcome back, Admin!");
      navigate("/admin");
    } catch (err) {
      const message =
        err.response?.data?.message || "Login failed. Please try again.";
      setError(message);
      toast.error(message);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="admin-login-page">
      <div className="admin-login-card glass-strong animate-scale-in" id="admin-login-card">
        {/* Shield Icon */}
        <div className="admin-icon-wrapper">
          <Shield size={32} />
        </div>

        <h1 className="admin-title">Platform Control Center</h1>
        <p className="admin-subtitle">
          Authorized Personnel Only
        </p>

        {/* Error Display */}
        {error && (
          <div className="error-banner">
            <AlertCircle size={16} />
            <span>{error}</span>
          </div>
        )}

        <form onSubmit={handleSubmit} className="admin-form" id="admin-login-form">
          <div className="input-group">
            <Mail size={18} className="input-icon" />
            <input
              type="email"
              placeholder="Admin email"
              value={email}
              onChange={(e) => setEmail(e.target.value)}
              className="auth-input"
              required
              id="admin-email"
            />
          </div>

          <div className="input-group">
            <Lock size={18} className="input-icon" />
            <input
              type={showPassword ? "text" : "password"}
              placeholder="Password"
              value={password}
              onChange={(e) => setPassword(e.target.value)}
              className="auth-input"
              required
              id="admin-password"
            />
            <button
              type="button"
              className="password-toggle"
              onClick={() => setShowPassword(!showPassword)}
              id="admin-toggle-password"
            >
              {showPassword ? <EyeOff size={18} /> : <Eye size={18} />}
            </button>
          </div>

          <button
            type="submit"
            className="btn-admin-login"
            disabled={loading}
            id="admin-submit-btn"
          >
            {loading ? (
              <>
                <Loader2 size={18} className="spin" />
                Authenticating...
              </>
            ) : (
              "Access Control Center"
            )}
          </button>
        </form>

        <p className="admin-notice">
          This portal is for authorized administrators only.
          <br />
          Contact the system administrator for access.
        </p>
      </div>
    </div>
  );
};

export default AdminLogin;

// angular-frontend/src/app/features/admin/login/admin-login.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { environment } from '../../../../environments/environment';

@Component({
  selector: 'app-admin-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './admin-login.component.html',
  styleUrls: ['./admin-login.component.css']
})
export class AdminLoginComponent {
  authService = inject(AuthService);
  router = inject(Router);

  email = environment.adminEmail || '';
  password = environment.adminPassword || '';
  showPassword = false;
  loading = false;
  error = '';

  submit() {
    this.error = '';
    if (!this.email || !this.password) {
      this.error = 'Please fill in all fields';
      return;
    }
    this.loading = true;
    this.authService.login(this.email, this.password).subscribe({
      next: (res) => {
        this.loading = false;
        if (res.user?.role !== 'admin') {
          this.error = 'Access denied. Admin credentials required.';
          // logout immediately to clear cookie
          this.authService.logout().subscribe();
          return;
        }
        this.router.navigate(['/admin']);
      },
      error: (err) => {
        this.loading = false;
        this.error = err.error?.message || 'Login failed. Please try again.';
      }
    });
  }
}

<div class="admin-login-page">
  <div class="admin-login-card">
    <!-- Shield Icon -->
    <div class="admin-icon-wrapper">
      <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>
    </div>

    <h1 class="admin-title">Platform Control Center</h1>
    <p class="admin-subtitle">Authorized Personnel Only</p>

    <!-- Error Banner -->
    <div class="error-banner" *ngIf="error">
      <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="12" y1="8" x2="12" y2="12"/><line x1="12" y1="16" x2="12.01" y2="16"/></svg>
      <span>{{ error }}</span>
    </div>

    <form (ngSubmit)="submit()" class="admin-form">
      <!-- Email -->
      <div class="input-group">
        <svg class="input-icon" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>
        <input type="email" placeholder="Admin email" [(ngModel)]="email" name="email" required class="auth-input" id="admin-email" />
      </div>

      <!-- Password -->
      <div class="input-group">
        <svg class="input-icon" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="3" y="11" width="18" height="11" rx="2" ry="2"/><path d="M7 11V7a5 5 0 0 1 10 0v4"/></svg>
        <input [type]="showPassword ? 'text' : 'password'" placeholder="Password" [(ngModel)]="password" name="password" required class="auth-input" id="admin-password" />
        <button type="button" class="password-toggle" (click)="showPassword = !showPassword" id="admin-toggle-password">
          <svg *ngIf="!showPassword" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/></svg>
          <svg *ngIf="showPassword" xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M17.94 17.94A10.07 10.07 0 0 1 12 20c-7 0-11-8-11-8a18.45 18.45 0 0 1 5.06-5.94M9.9 4.24A9.12 9.12 0 0 1 12 4c7 0 11 8 11 8a18.5 18.5 0 0 1-2.16 3.19m-6.72-1.07a3 3 0 1 1-4.24-4.24"/><line x1="1" y1="1" x2="23" y2="23"/></svg>
        </button>
      </div>

      <button type="submit" class="btn-admin-login" [disabled]="loading" id="admin-submit-btn">
        <span *ngIf="loading">Authenticating...</span>
        <span *ngIf="!loading">Access Control Center</span>
      </button>
    </form>

    <p class="admin-notice">
      This portal is for authorized administrators only.<br />
      Contact the system administrator for access.
    </p>
  </div>
</div>
