// react-frontend/src/components/Navbar.jsx
import { useState } from "react";
import { useLocation, useNavigate } from "react-router-dom";
import { useAuth } from "../context/AuthContext";
import { LogOut, User, ChevronDown, Briefcase, Shield } from "lucide-react";
import toast from "react-hot-toast";

/**
 * Navigation Bar Component
 * Shows logo, navigation links, and user menu when authenticated
 * Glass morphism styling with smooth animations
 */
const Navbar = () => {
  const { user, isAuthenticated, logout } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();
  const [showDropdown, setShowDropdown] = useState(false);

  // Hide Navbar on dashboard routes, except for /dashboard/jobs
  if ((location.pathname.startsWith("/dashboard") && location.pathname !== "/dashboard/jobs") || location.pathname.startsWith("/recruiter/dashboard") || location.pathname.startsWith("/admin")) {
    return null;
  }

  const handleLogout = async () => {
    await logout();
    toast.success("Logged out successfully");
    navigate("/");
    setShowDropdown(false);
  };

  const handleDashboard = () => {
    if (!user) return;
    const dashboardRoutes = {
      jobseeker: "/dashboard",
      recruiter: "/recruiter/dashboard",
      admin: "/admin",
    };
    navigate(dashboardRoutes[user.role] || "/");
    setShowDropdown(false);
  };

  return (
    <nav className="navbar glass" id="main-navbar">
      <div className="navbar-container">
        {/* Left Side: Logo & Main Navigation Links */}
        <div style={{ display: "flex", alignItems: "center", gap: "var(--space-8)" }}>
          {/* Logo */}
          <div className="navbar-logo" onClick={() => navigate("/")} id="navbar-logo">
            <div className="logo-icon">
              <Briefcase size={22} />
            </div>
            <span className="logo-text">JobPortal</span>
          </div>

          {/* Navigation Links */}
          <div className="navbar-links">
            <a href="/jobs" className="nav-link">Find Jobs</a>
            <a href="/#features" className="nav-link">Features</a>
            <a href="/#about" className="nav-link">About</a>
          </div>
        </div>

        {/* Right Side Actions */}
        <div className="navbar-right">
          {/* Shield Icon Link for admin login page (Angular) */}
          <button
            className="btn-shield-admin"
            onClick={() => window.location.href = "http://localhost:4200/admin/login"}
            title="Authorized Personnel Only"
            id="admin-portal-link"
          >
            <Shield size={20} />
          </button>

          {isAuthenticated && user ? (
            <div className="user-menu">
              <button
                className="user-menu-trigger"
                onClick={() => setShowDropdown(!showDropdown)}
                id="user-menu-trigger"
              >
                <div className="user-avatar">
                  {user.name?.charAt(0).toUpperCase()}
                </div>
                <span className="user-name">{user.name}</span>
                <ChevronDown
                  size={16}
                  className={`chevron ${showDropdown ? "rotated" : ""}`}
                />
              </button>

              {showDropdown && (
                <div className="dropdown-menu glass-strong animate-scale-in" id="user-dropdown">
                  <div className="dropdown-header">
                    <p className="dropdown-user-name">{user.name}</p>
                    <p className="dropdown-user-email">{user.email}</p>
                    <span className="dropdown-role-badge">{user.role}</span>
                  </div>
                  <div className="dropdown-divider" />
                  <button
                    className="dropdown-item"
                    onClick={handleDashboard}
                    id="dropdown-dashboard"
                  >
                    <User size={16} />
                    Dashboard
                  </button>
                  <button
                    className="dropdown-item dropdown-item-danger"
                    onClick={handleLogout}
                    id="dropdown-logout"
                  >
                    <LogOut size={16} />
                    Logout
                  </button>
                </div>
              )}
            </div>
          ) : (
            <button
              className="btn-get-started"
              onClick={() => navigate("/login")}
              id="btn-get-started"
            >
              Login
            </button>
          )}
        </div>
      </div>

      {/* Click outside to close dropdown */}
      {showDropdown && (
        <div
          className="dropdown-overlay"
          onClick={() => setShowDropdown(false)}
        />
      )}
    </nav>
  );
};

export default Navbar;

// angular-frontend/src/app/shared/components/navbar/navbar.component.ts
import { Component, inject, OnInit, OnDestroy } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, NavigationEnd } from '@angular/router';
import { AuthService } from '../../../core/services/auth.service';
import { Subscription } from 'rxjs';
import { filter } from 'rxjs/operators';
import { environment } from '../../../../environments/environment';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './navbar.component.html',
  styleUrls: ['./navbar.component.css']
})
export class NavbarComponent implements OnInit, OnDestroy {
  authService = inject(AuthService);
  router = inject(Router);

  user: any = null;
  isAuthenticated = false;
  showDropdown = false;
  showNavbar = true;
  isScrolled = false;

  private subs = new Subscription();

  ngOnInit(): void {
    // 1. Listen to auth state changes
    this.subs.add(
      this.authService.currentUser$.subscribe((user: any) => {
        this.user = user;
      })
    );
    this.subs.add(
      this.authService.isAuthenticated$.subscribe(auth => {
        this.isAuthenticated = auth;
      })
    );

    // 2. Hide navbar on dashboard routes (parity with React)
    this.checkNavbarVisibility(this.router.url);
    this.subs.add(
      this.router.events.pipe(
        filter(event => event instanceof NavigationEnd)
      ).subscribe((event: any) => {
        this.checkNavbarVisibility(event.urlAfterRedirects);
        this.showDropdown = false; // Close dropdown on navigate
      })
    );

    // 3. Scroll listener for dynamic background styling
    if (typeof window !== 'undefined') {
      window.addEventListener('scroll', this.handleScroll);
    }
  }

  ngOnDestroy(): void {
    this.subs.unsubscribe();
    if (typeof window !== 'undefined') {
      window.removeEventListener('scroll', this.handleScroll);
    }
  }

  handleScroll = (): void => {
    this.isScrolled = window.scrollY > 10;
  };

  private checkNavbarVisibility(url: string): void {
    this.showNavbar = !(
      url.startsWith('/dashboard') ||
      url.startsWith('/recruiter/dashboard') ||
      url.startsWith('/admin')
    );
  }

  toggleDropdown(): void {
    this.showDropdown = !this.showDropdown;
  }

  closeDropdown(): void {
    this.showDropdown = false;
  }

  navigateTo(path: string): void {
    this.router.navigate([path]);
  }

  handleLogoClick(): void {
    this.router.navigate(['/']);
  }

  handleDashboard(): void {
    if (!this.user) return;
    const dest = this.authService.getDashboardRoute(this.user.role);
    if (dest.isAngular) {
      this.router.navigate([dest.path]);
    } else {
      window.location.href = `${environment.reactAppUrl}${dest.path}`;
    }
    this.showDropdown = false;
  }

  handleLogout(): void {
    this.authService.logout().subscribe({
      next: () => {
        this.router.navigate(['/']);
        this.showDropdown = false;
      },
      error: () => {
        // Fallback redirect
        this.router.navigate(['/']);
        this.showDropdown = false;
      }
    });
  }

  goToAdminLogin(): void {
    window.location.href = `${environment.reactAppUrl}/admin/login`;
  }
}

<nav class="navbar glass" [class.scrolled]="isScrolled" *ngIf="showNavbar" id="main-navbar">
  <div class="navbar-container">
    <!-- Left Side: Logo & Main Navigation Links -->
    <div style="display: flex; align-items: center; gap: var(--space-8);">
      <!-- Logo -->
      <div class="navbar-logo" (click)="handleLogoClick()" id="navbar-logo">
        <div class="logo-icon">
          <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
            <rect x="2" y="7" width="20" height="14" rx="2" ry="2"></rect>
            <path d="M16 21V5a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16"></path>
          </svg>
        </div>
        <span class="logo-text">JobPortal</span>
      </div>

      <!-- Navigation Links -->
      <div class="navbar-links">
        <a class="nav-link" (click)="navigateTo('/jobs')">Find Jobs</a>
        <a class="nav-link" href="#features">Features</a>
        <a class="nav-link" href="#about">About</a>
      </div>
    </div>

    <!-- Right Side Actions -->
    <div class="navbar-right">
      <!-- Shield Icon Link for admin login page -->
      <button
        class="btn-shield-admin"
        (click)="goToAdminLogin()"
        title="Authorized Personnel Only"
        id="admin-portal-link"
      >
        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
          <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
        </svg>
      </button>

      <ng-container *ngIf="isAuthenticated && user; else unauthBlock">
        <div class="user-menu">
          <button
            class="user-menu-trigger"
            (click)="toggleDropdown()"
            id="user-menu-trigger"
          >
            <div class="user-avatar">
              {{ user.name?.charAt(0).toUpperCase() }}
            </div>
            <span class="user-name">{{ user.name }}</span>
            <svg
              width="16"
              height="16"
              viewBox="0 0 24 24"
              fill="none"
              stroke="currentColor"
              stroke-width="2"
              stroke-linecap="round"
              stroke-linejoin="round"
              class="chevron"
              [class.rotated]="showDropdown"
            >
              <polyline points="6 9 12 15 18 9"></polyline>
            </svg>
          </button>

          <div class="dropdown-menu glass-strong animate-scale-in" *ngIf="showDropdown" id="user-dropdown">
            <div class="dropdown-header">
              <p class="dropdown-user-name">{{ user.name }}</p>
              <p class="dropdown-user-email">{{ user.email }}</p>
              <span class="dropdown-role-badge">{{ user.role }}</span>
            </div>
            <div class="dropdown-divider"></div>
            <button
              class="dropdown-item"
              (click)="handleDashboard()"
              id="dropdown-dashboard"
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-right: 8px;">
                <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                <circle cx="12" cy="7" r="4"></circle>
              </svg>
              Dashboard
            </button>
            <button
              class="dropdown-item dropdown-item-danger"
              (click)="handleLogout()"
              id="dropdown-logout"
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" style="margin-right: 8px;">
                <path d="M9 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h4"></path>
                <polyline points="16 17 21 12 16 7"></polyline>
                <line x1="21" y1="12" x2="9" y2="12"></line>
              </svg>
              Logout
            </button>
          </div>
        </div>
      </ng-container>

      <ng-template #unauthBlock>
        <button
          class="btn-get-started"
          (click)="navigateTo('/login')"
          id="btn-get-started"
        >
          Login
        </button>
      </ng-template>
    </div>
  </div>

  <!-- Click outside to close dropdown -->
  <div
    class="dropdown-overlay"
    *ngIf="showDropdown"
    (click)="closeDropdown()"
  ></div>
</nav>
